### ISSUE TITLE
Removing single quotes and hashtags from data files

### ISSUE THREAD

**Issue by DavidOry** [MetropolitanTransportationCommission/onboard-surveys#14]
You can see by the data file names for the survey instruments read into the standard survey builder that I manually removed hashtags and single quotes from the files prior to reading them into R. This is clunky and can be avoided by:

(1) Changing the `comment.char` parameter in `read.table`, which is the basis is `read.csv`. The default is `#'.

(2) Changing the `quote` parameter to `quote="\""` (the default includes the single quote as well).

**Comment by jhelsel11** [comment]
Where is `read.table` or `quote` in `Build Standard Database.Rmd`? I tried using `read.csv` on the Caltrain data without any additional parameters and it appeared to capture everything needed. (Perhaps that's not what you're referring to?)

**Comment by DavidOry** [comment]
See above reference for commit fix.
