### ISSUE TITLE
Transfer inconsistency in standard database

### ISSUE THREAD

**Issue by DavidOry** [MetropolitanTransportationCommission/onboard-surveys#19]
Operators and/or technologies need to be added to the `set_operator_name` method to make sure the implied transfers (which is computed by looking at the transfer route names) is the same as the stated transfers (which is the survey response). The `debug_transfer` dataframe can be examined to see what operators need to be added.

**Comment by DavidOry** [comment]
@jhelsel11: we fixed this in #25, aside from the one issue with SF Muni where the respondent had more than three after transfers. Can you detail the record numbers in which that happened here for @shimonisrael's reference?

**Comment by jhelsel11** [comment]
I found 2 muni records with 4th degree transfers. Their ID and transfers are:
      id__________final_trip_to_fourth_route
25955_____Golden Gate 29 San Rafael - Larkspur Landing - Fairfax - Manor
31474_____SamTrans 250 Downtown San Mateo College of San Mateo

**Comment by DavidOry** [comment]
Great. Closing for now as the software is working, but is consciously limited to 3 transfers to/from the intercept route.
